### ISSUE TITLE
WAFER-RK3588 display issue

### ISSUE THREAD

**Issue by sinyfu** [QNAP-android-internal/kernel-rk#1]
Hello team,

We purchased a WAFER-RK3588 unit but have encountered some issues (Serial number: 70-006B675-000-102-RS).

We migrated an 11.6" HDMI touchscreen, which works well after the support you provided. However, we noticed that the resolution is set to 1280x800, and there are black bars on both sides of the display.

Today, your PM provided a command to enable fullscreen: setprop persist.sys.rotation.einit-1 true

This command worked, but it brought some side effects:
i. The image quality appears very poor.
ii. The touch input becomes inverted in Netflix. Do we need to rotate the idc file to address this? (as shown in the video below)
Is there a solution for these issues?

![netflix_touch_issue](https://github.com/user-attachments/assets/81b7d48d-aaca-439f-ba1f-5bb5e103241f)

For us, the most effective solution so far is to use HDMI as the primary display, as Netflix plays correctly this way. Are there any side effects to modifying it this way?

![netflix_touch_work](https://github.com/user-attachments/assets/c9dc9408-a51e-4889-b707-8807ff16b097)

Additionally, we are experiencing issues when using a UVC camera, where the camera sometimes fails to start, as described below: After feedback from your PM, we conducted further tests and found that the USB 2.0 port works fine for the camera. We are okay with proceeding this way for development purposes. Thank you.

![camera_usb3](https://github.com/user-attachments/assets/e4aed112-3361-454a-9a95-5ad6f754761c)

**Comment by lc-wang** [comment]
Hi @sinyfu ,

For the display issue, please apply the attached patches. 
Please try it out and let me know if you have any questions.
Thank you.

[0001-rk3588-rk3588_b675.mk-use-HDMI-as-primary-display.patch](https://github.com/user-attachments/files/17770247/0001-rk3588-rk3588_b675.mk-use-HDMI-as-primary-display.patch)
[0002-Revert-rk3588-BoardConfig-rotaion-90-degrees-to-set-.patch](https://github.com/user-attachments/files/17770248/0002-Revert-rk3588-BoardConfig-rotaion-90-degrees-to-set-.patch)
[0003-rk3588-rk3588_b675.mk-correct-rotation-of-other-disp.patch](https://github.com/user-attachments/files/17770249/0003-rk3588-rk3588_b675.mk-correct-rotation-of-other-disp.patch)

**Comment by sinyfu** [comment]
These three patches are fine for us, thank you. The only issue is that the UVC camera cannot be opened randomly. When will this be resolved?

**Comment by lc-wang** [comment]
Hi @sinyfu,

We will resolve the UVC camera issue in Android 14.

**Comment by sinyfu** [comment]
Great! Looking forward your next release.
